CREATE TABLE [dbo].[ChangBay](
	[MaChangBay] [nvarchar](20) NOT NULL,
	[MaSanBayDi] [nvarchar](10) NULL,
	[MaSanBayDen] [nvarchar](10) NULL,
 CONSTRAINT [PK_ChangBay] PRIMARY KEY CLUSTERED 
(
	[MaChangBay] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


