CREATE TABLE [dbo].[HangVe](
	[MaHangVe] [nvarchar](10) NOT NULL,
	[TenHangVe] [nvarchar](50) NULL,
 CONSTRAINT [PK_HangVe] PRIMARY KEY CLUSTERED 
(
	[MaHangVe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


